### ISSUE TITLE
addAnnotations to mapView

### ISSUE THREAD

**Issue by djminikin** [Constantine-Fry/das-quadrat#18]
I can't find your email.
The problem: I'm trying to add annotations to the mapView from venueItems but just can't. (Map view loaded without any annotation)
My session request did receive response:  Optional(200) and in console I can see venue description and etc. I also checked your Foursquare-API-v2 demo project. I think something wrong with my proccessAnnotations() method or in way in which I added your library.
![screen shot 2015-01-11 at 3 23 53 am](https://cloud.githubusercontent.com/assets/4456735/5693986/6a03a260-9942-11e4-9006-057b712ced5e.png)

What I missed ?
Thank you in advance for your advice.

import Foundation
import UIKit
import CoreLocation
import MapKit
class MapViewController: UIViewController, MKMapViewDelegate, CLLocationManagerDelegate {

    var session : Session!
    var locationManager: CLLocationManager!
    var venueItems : [[String: AnyObject]]?
    var junkAnotations =  MKPointAnnotation()
    
    @IBOutlet weak var mapOutlet: MKMapView!
    
    override func viewDidLoad() {
        super.viewDidLoad()

        session = Session.sharedSession()
        session.logger = ConsoleLogger()

        //Setup Location Manager
        locationManager = CLLocationManager()
        locationManager.delegate = self
        locationManager.desiredAccuracy = kCLLocationAccuracyNearestTenMeters
        locationManager.requestAlwaysAuthorization()
        let status = CLLocationManager.authorizationStatus()
        if status == .NotDetermined {
            locationManager.requestWhenInUseAuthorization()
        } else if status == .AuthorizedWhenInUse || status == .Authorized {
            locationManager.startUpdatingLocation()
        }
    
        mapOutlet.showsBuildings = true
        mapOutlet.delegate = self
        mapOutlet.mapType = .Standard
        
}

//MARK: LOCATION MANAGER
    
    func createLocationManager(#startImmediately: Bool){
        locationManager = CLLocationManager()
        if let manager = locationManager{
            println("Successfully created the location manager")
            manager.delegate = self
            if startImmediately{
                manager.startUpdatingLocation()
            }
        }
    }

    func locationManager(manager: CLLocationManager!,
        didChangeAuthorizationStatus status: CLAuthorizationStatus){

            print("The authorization status of location services is changed to: ")

            switch CLLocationManager.authorizationStatus(){
            case .Denied:
                println("Denied")
                
            case .NotDetermined:
                println("Not determined")
                
            case .Restricted:
                println("Restricted")

            default:
               println("Good")

            }
    }

     func locationManager(manager: CLLocationManager!, didUpdateToLocation newLocation: CLLocation!, fromLocation oldLocation: CLLocation!) {
        if venueItems == nil {
            getVenuesForLocation()
        }
        showUserLocationOnMapView()
        proccessAnnotations()
        locationManager.stopUpdatingLocation()
    }
    
//MARK: SHOW USER LOCATION
    
    /* We call this method when we are sure that the user has given
    us access to her location */
    func showUserLocationOnMapView(){
        mapOutlet.showsUserLocation = true
        mapOutlet.userTrackingMode = .Follow
        mapOutlet.camera.altitude *= 1.3;
        mapOutlet.showsBuildings = true
    }
 
// MARK: ProccessAnnotations
    
    func proccessAnnotations () {
        self.mapOutlet.addAnnotations(self.venueItems)
    }
    
    
// MARK: SHOW NEARBY VENUES ON MAP
 
func getVenuesForLocation() {
    
            let location = self.locationManager.location
    
            var kebab = [Parameter.query:"coffee"]
            kebab += location.parameters()
            kebab += [Parameter.openNow:"1"]
            kebab += [Parameter.radius:"2500"]
            kebab += [Parameter.altAcc:"100"]
            kebab += [Parameter.limit:"20"]
    
            let searchTask = session.venues.explore(kebab) {
                (result) -> Void in
                if self.venueItems != nil {
                    return
                }
                if !NSThread.isMainThread() {
                    fatalError("Sorry, error! Please try to reload app.")
                }
                if result.response != nil {
                    if let groups = result.response!["groups"] as [[String: AnyObject]]?  {
                        var venues = [[String: AnyObject]]()
                        for group in groups {
                            let items = group["items"] as [[String: AnyObject]]!
                            venues += items
                        }
                        self.venueItems = venues
                        
                    }
                    println(self.venueItems?.count)
                    
                } else if result.error != nil && !result.isCancelled() {
                    
                }
            }
        searchTask.start()
}
}

**Comment by Constantine-Fry** [comment]
1. To display received venues on map, you should call `processAnnotations` method in completion handler of `searchTask`.

2. Your `processAnnotations` method quiet incorrect. `addAnnotation` method accepts objects that conforms to [`MKAnnotation`](https://developer.apple.com/library/ios/documentation/MapKit/Reference/MKAnnotation_Protocol/index.html) protocol, but you are passing dictionary `[String: AnyObject]`. You should manually convert received dictionary to your custom objects that conforms to `MKAnnotation`. 
Read documentation for [`addAnnotation`](https://developer.apple.com/library/ios/documentation/MapKit/Reference/MKMapView_Class/#//apple_ref/occ/instm/MKMapView/addAnnotations:) method.

![screen shot 2015-01-11 at 10 24 50](https://cloud.githubusercontent.com/assets/239692/5694820/1e976818-997c-11e4-9a0d-922a94e8e1d1.png)
3. You request authorisation for user location in `viewDidLoad` incorrectly. You should not call `requestAlwaysAuthorization` method always, only when status is `NotDetermined `.

**Comment by djminikin** [comment]
Thank you very much for your detailed answer.
