### ISSUE TITLE
Expose accessToken through QuadratTouch.framework

### ISSUE THREAD

**Issue by evanwdavis** [Constantine-Fry/das-quadrat#20]
Would it be possible to expose the Session's Configuration's accessToken property? I'm working on a combo web app / iOS app that shares the same accessToken, so if they connect via the iOS app I need to send it to the web app (so they don't have to connect twice). 

thanks!

**Comment by Constantine-Fry** [comment]
Ready it's public now https://github.com/Constantine-Fry/das-quadrat/commit/2e9beeafa4d738fc98199f1e802adc45dfdd5478. But this access token not saved in Keychain, it's intends to be used in tests.
