### ISSUE TITLE
Quadrat.framework: No such file or directory

### ISSUE THREAD

**Issue by vani2** [Constantine-Fry/das-quadrat#22]
You wrote iOS 7.0+, but embedded frameworks are supported by iOS 8+. Please change ReadMe until you support 7.0+. If you try build project with iOS 7 target, error occurred `Quadrat.framework: No such file or directory`.

**Comment by Constantine-Fry** [comment]
Thank you. I have updated readme. You can still use das-quadrat on iOS 7 if you add source code files directly into your project.

**Comment by vani2** [comment]
It's a good practice to add readme how to install it via git submodule for < iOS 8.
