### ISSUE TITLE
Does not have a member named 'location'

### ISSUE THREAD

**Issue by cklimkowsky** [Constantine-Fry/das-quadrat#26]
Following the usage instructions for a search request in the README, I tried using the sample code in a ViewController and got the following error:

'ViewController' does not have a member named 'location'

Where am I supposed to make a search request?

**Comment by Constantine-Fry** [comment]
Well, the code in readme is just a snippet. There is a demo project in repository. You can check out [ExploreViewController.swift](https://github.com/Constantine-Fry/das-quadrat/blob/develop/Demo/Demo-iOS/Demo-iOS/ExploreViewController.swift) and see how to get a location.
