### ISSUE TITLE
Is it possible to use this from an Obj-C app?

### ISSUE THREAD

**Issue by benguild** [Constantine-Fry/das-quadrat#27]
```
@import QuadratTouch;
```
 ... set "Embeds Swift Code" to "yes", etc.

Wasn't sure how to interface with this from Objective-C because the code is different. Will it work, and is it supported?

**Comment by Constantine-Fry** [comment]
Classes in the library are not prefixed with `@objc`. So you can't use it from objc code.
But you always can prepare a PR :)

**Comment by benguild** [comment]
a PR?

**Comment by Constantine-Fry** [comment]
PR = Pull Request :)

It's my personal opinion that we should use Swift for new stuff. Do you think differently?

**Comment by benguild** [comment]
So do a pull request and add it to each of the headers?

I still feel like Swift is a bit new. I like it, but I want it to mature a bit more before making the switch. Would be nice to have the reverse compatibility either way. Let me know what I should do here.

**Comment by benguild** [comment]
![2015-04-21 4 39 03 pm](https://cloud.githubusercontent.com/assets/1185659/7247492/07b31f58-e845-11e4-961f-94237c555770.png)

**Comment by benguild** [comment]
It looks like the lack of struct support in Objective-C is going to kill this migration off for now unless someone feels like writing a wrapper. :(

**Comment by benguild** [comment]
This is kind of a bummer because there are a lot of people that haven't moved to Swift yet, or are trying to maintain active projects that can't be completely rewritten. It'd be nice to have Objective-C support, because Apple designed the Swift language to support both and provide portability.

It's a shame that struct support is missing and the Swift syntax keeps changing, because it seems like a pain to get this to work as easily as Apple implies?

**Comment by benguild** [comment]
I was able to write a Swift wrapper for the functions I needed and interface with that using Objective-C.

**Comment by billy84** [comment]
Hi @benguild 
How are you?
Could you share the Swift wrapper you wrote?

Thanks

**Comment by benguild** [comment]
Hello again, @billy84!
The Swift wrapper I ended up writing is for a specific purpose and only covers the functions that I need/use, so it would not be suitable for public release nor for your use... most likely.

As I mentioned in the other issue, you should write your own wrapper that you can call from your Objective-C code, or simply rewrite your own class(es) that need to call this library in Swift. Either one is probably your best bet, but if you want to keep the bulk of your code in Objective-C, you need to write the wrapper as I have suggested and as you have acknowledged.

Good luck! Let us know if you run into any issues related to the library, or if you have any code you want to share with everyone that could be utilized by others.

**Comment by billy84** [comment]
Hello @benguild 
Thank you for your suggestion.
I will try to do so.
Good luck you too!
