### ISSUE TITLE
Cocoapods?

### ISSUE THREAD

**Issue by rjgdesign** [Constantine-Fry/das-quadrat#29]
Would it be possible to get this in cocoa pods?

**Comment by Constantine-Fry** [comment]
I will take a look. They have support for iOS 8 frameworks now.

**Comment by mwaterfall** [comment]
+1

**Comment by ArtSabintsev** [comment]
+1

**Comment by mike25x** [comment]
+1

**Comment by paveltaran** [comment]
+1

**Comment by intellitour** [comment]
+1

**Comment by tronador** [comment]
+1

**Comment by benguild** [comment]
With Objective-C support, please! :)

**Comment by hasankacar** [comment]
+1

**Comment by apobbati** [comment]
+1

**Comment by keitaito** [comment]
+1 please! :)

**Comment by Constantine-Fry** [comment]
I have adde this library to Cocopoads. Let me know if it doesn't work for you well.

![screen shot 2015-08-23 at 18 28 10](https://cloud.githubusercontent.com/assets/239692/9429091/b9857cc2-49c4-11e5-9e89-f59192d035f6.png)
