### ISSUE TITLE
Does this support using a custom/native UI for the Authorization process?

### ISSUE THREAD

**Issue by xiaoxion** [Constantine-Fry/das-quadrat#31]
I am working on an app that has a coherent design. I was hoping on extending that to the login portion but from what I saw, the library sends it's authorization to a foursquare web view and retrieves the token when it is done. Is there a way to customize this?

**Comment by Constantine-Fry** [comment]
No, authorisation should be done via webpage or Foursqurae application. It can't not be customised.
