### ISSUE TITLE
Swift 2 Support?

### ISSUE THREAD

**Issue by ryanmclaughlin** [Constantine-Fry/das-quadrat#33]
Hey there, just wondering if you think you'll be able to support Swift 2?

Best

**Comment by Constantine-Fry** [comment]
Yes, I do plan to migrate to Swift 2.

**Comment by ryanmclaughlin** [comment]
@Constantine-Fry :+1: Great to hear.

**Comment by kdgwill** [comment]
Has their been any update on the Swift 2.0 front?

**Comment by benguild** [comment]
+1, am currently reverted to `Foursquare-API-v2` on an app because this won't run in Xcode 7.

**Comment by Constantine-Fry** [comment]
Well, Swift 2 support will come soon. I was planing to do it, this weekend.

**Comment by Constantine-Fry** [comment]
And here we go.
https://github.com/Constantine-Fry/das-quadrat/pull/40
