### ISSUE TITLE
AuthorizerViewController should adopt bar tint colors of its presentingViewController.

### ISSUE THREAD

**Issue by benguild** [Constantine-Fry/das-quadrat#38]
The bar and button tint colors should match.

**Comment by Constantine-Fry** [comment]
Well, tint color should be inherited from superview, not from presenting view controller. UIView's tint colour propagated on view hierarchy, not on view controllers hierarchy. You should be sure that you set tint colour on your window.

Regarding the style of navigation bar. How do you want to style it?

**Comment by benguild** [comment]
Created a pull-request.

**Comment by benguild** [comment]
Hey I think this should be configurable separately. For example, it sets all of the UIAlertController colors globally for the app to something else just to configure this one modal. I forgot about that.

I would suggest returning the view controller to the user so that it can be manually presented or configured. Like: https://github.com/TransitApp/SVWebViewController

Or, at least let us provide a tintColor.

**Comment by Constantine-Fry** [comment]
I made a commit, to make public AuthorizationNavigationController. You can use this class with UIAppearance, to set tint color. I will make a new Cocoapod update this weekend.


https://github.com/Constantine-Fry/das-quadrat/commit/fb25260a92684c69884abd58265ea12f8d463019
