### ISSUE TITLE
Compile error on Swift 2

### ISSUE THREAD

**Issue by gvimlan95** [Constantine-Fry/das-quadrat#41]
Hi
It's written that it is currently supporting Swift 2 but sadly I m getting compile error.

![screen shot 2015-09-02 at 7 36 17 pm](https://cloud.githubusercontent.com/assets/9544447/9630021/e963a5f8-51a9-11e5-8f71-7b3598d0b295.png)

**Comment by Constantine-Fry** [comment]
What get version tag did use?

**Comment by Constantine-Fry** [comment]
Can you please check version 1.1.1?

**Comment by gvimlan95** [comment]
@Constantine-Fry  Have solved it. Was on the wrong version. Thank you :)
