### ISSUE TITLE
mode parameter should be optional

### ISSUE THREAD

**Issue by gfhuertac** [Constantine-Fry/das-quadrat#44]
When using the venues API, the mode parameter is always included.
However, this causes that the contact information of the venues is not included.
Try the following:

https://api.foursquare.com/v2/venues/explore?ll=40.759211,-73.984638&v=20140503&oauth_token=<TOKEN>

versus

https://api.foursquare.com/v2/venues/explore?ll=40.759211,-73.984638&m=foursquare&v=20140503&oauth_token=<TOKEN>

The first request will include the contact information from the venues, while the second one will not include it. 
Therefore, the mode should be optional so we can get the desired information.

**Comment by Constantine-Fry** [comment]
Yes, you are right. It should be optional. Thanks for the PR.
