### ISSUE TITLE
Undocumented `venues/VENUE_ID/ok` Endpoint

### ISSUE THREAD

**Issue by zshannon** [Constantine-Fry/das-quadrat#46]
There's an undocumented Venue action endpoint for toggling a neutral/ok rating. Works exactly like `venues/VENUE_ID/like` and `venues/VENUE_ID/dislike`. It's used by the native Foursquare app, so it's probably stable, and there's no great reason why it's not included in the public documentation.

Would you accept a PR adding support for it?

**Comment by Constantine-Fry** [comment]
Hi, I think it's should be already in `Venues` class.

![screen shot 2015-12-29 at 11 30 05](https://cloud.githubusercontent.com/assets/239692/12033082/8ed472ac-ae1f-11e5-913f-33b6e4685bed.png)
![screen shot 2015-12-29 at 11 29 58](https://cloud.githubusercontent.com/assets/239692/12033085/97530588-ae1f-11e5-8e40-1cbf6baf3905.png)

**Comment by Constantine-Fry** [comment]
Oh, I'm very sorry. I've misread you. I thought you need like and dislike methods.
I wouldn't add any private calls into this library. I think it's incorrect to make someones private stuff public.

**Comment by zshannon** [comment]
Gotcha, and I understand. Thanks for considering!
