### ISSUE TITLE
Multi Endpoint's HTTPMethod should be optional (POST or GET)

### ISSUE THREAD

**Issue by columbooo** [Constantine-Fry/das-quadrat#49]
Hi,
I want to use Multi Endpoint to save requests. I've noticed that when I use with GET method then the X-RateLimit-Limit in the response header is 5000, however, when I use with POST method then its value is 500. Could you support it? Or would you accept a PR that supports it?

**Comment by Constantine-Fry** [comment]
Hi, I'm sorry this response header sent by the Foursquare server. It has nothing to do with the library.

**Comment by laszloilonka** [comment]
Hi, I mean that in Multi.swift file in your library we can use "GET" as HTTPMethod at line 43. Could you, please look into them?
