### ISSUE TITLE
multiTask implementation

### ISSUE THREAD

**Issue by taktikal17** [Constantine-Fry/das-quadrat#51]
Hey,

I am trying to query multiple categoryIds. With one it obviously works well:

          let searchTask = session.venues.search(parameters) {
          ...
          searchTask.start()
          }

with:

            var parameters = location.parameters()
            parameters += [Parameter.categoryId: "4bf58dd8d48988d103951735"]
            parameters += [Parameter.radius: "2000"]
            parameters += [Parameter.limit: "50"]

When I add another:

            var parameters1 = location.parameters()
            parameters1 += [Parameter.categoryId: "52f2ab2ebcbc57f1066b8b23"]
            parameters1 += [Parameter.radius: "2000"]
            parameters1 += [Parameter.limit: "50"]

and try to use the multi Tasks, it goes wrong, I have no clear idea how to implement the completionHandler:

             let multiTask = session.multi.get(tasks: [parameters, parameters1], completionHandler:          ResponseClosure) {
              ...
              multiTask.start()
              }

Thank you a lot!!!!!!!!!!!!!!!

**Comment by koogawa** [comment]
> let multiTask = session.multi.get(tasks: [parameters, parameters1], completionHandler: 

`tasks` argument is invalid. You can do so like this:

```
        var parameters = [Parameter.query:strippedString]
        parameters += self.location.parameters()
        parameters += [Parameter.categoryId: "4bf58dd8d48988d103951735"]
        let task = session.venues.search(parameters)
        
        var parameters1 = [Parameter.query:strippedString]
        parameters1 += self.location.parameters()
        parameters1 += [Parameter.categoryId: "4bf58dd8d48988d10c951735"]
        let task1 = session.venues.search(parameters1)
        
        let multiTask = self.session.multi.get([task, task1]){
            (result) -> Void in
            
            print ("result:", result.results) // Use result not response, If you use multi task
        }
        multiTask.start()
```

**POINT:**

You have to use `result.results` (not result.response), If you use multi task.

**Comment by Constantine-Fry** [comment]
Nice. @koogawa thanks for answering :)
