### ISSUE TITLE
Missing Contact Field in Response

### ISSUE THREAD

**Issue by flohei** [Constantine-Fry/das-quadrat#52]
I use this project to find information about venues in my app. I only query public information; I don't have my users authenticate. Works as advertised so far. Somehow, the `contact` field stays empty/is not there. The [API docs](https://developer.foursquare.com/docs/responses/venue) suggest, that I should be able to access those information in a similar fashion to the location data, for example.

Is this an error on my end or is this some kind of known issue?

Thank you!

**Comment by Constantine-Fry** [comment]
What end point do you use?

**Comment by flohei** [comment]
I'm just using `venues.search`, which, I believe, translates to the `venues` endpoint, right?

**Comment by Constantine-Fry** [comment]
You can set `mode` to nil and it will work for you.
```swift
            var configuration = Configuration(client:client)
            configuration.mode = nil
```
I have updated the demo application: https://github.com/Constantine-Fry/das-quadrat/commit/7b9411a96557b718ca47c8f50a25e39af729d816.
