### ISSUE TITLE
Access Token

### ISSUE THREAD

**Issue by sdtaheri** [Constantine-Fry/das-quadrat#53]
Hi,
Isn't there a way to get access token after authorization is done and shared Session is created?
I need it for sending to my own server.

Thanks,
Saeed

**Comment by Constantine-Fry** [comment]
Hi,
I have added a function to retrieve access token. It's in develop branch now.
https://github.com/Constantine-Fry/das-quadrat/commit/87e967bcbe05d657ea0c333be08e7da675b294fd
