### ISSUE TITLE
why is parameter 'locale' internal use only?

### ISSUE THREAD

**Issue by senseluo** [Constantine-Fry/das-quadrat#56]
hi @Constantine-Fry ,

I have noticed that parameter 'locale' internal use only?
Is that your intention? or is there any approach to pass locale for the request?

Thank you!

**Comment by Constantine-Fry** [comment]
Hi, check out `Configuration` class. It has `locale` as a public property.

**Comment by senseluo** [comment]
Thank you for quick reply. Got it.
