### ISSUE TITLE
Migrating to Swift 3

### ISSUE THREAD

**Issue by darthpelo** [Constantine-Fry/das-quadrat#60]
Hi @Constantine-Fry have you planned the migration of the pods to Swift 3?

**Comment by darthpelo** [comment]
Hi @Constantine-Fry I am working on it following the good post by @jessesquires [Migrating to Swift 3](http://www.jessesquires.com/migrating-to-swift-3/?utm_campaign=This%2BWeek%2Bin%2BSwift&utm_medium=email&utm_source=This_Week_in_Swift_97)

For now I finished the migration to [Swift 2.3](https://github.com/darthpelo/das-quadrat) and I am testing with this [project](https://github.com/darthpelo/SurviveAmsterdam/tree/swift2.3).

Hope to be helpful :)

**Comment by benguild** [comment]
+1

**Comment by benguild** [comment]
A push of 2.3 support would be nice. I'm currently seeing some build errors even in your fork, @darthpelo:

<img width="266" src="https://cloud.githubusercontent.com/assets/1185659/17687201/1f943e64-63ae-11e6-9844-5de20d36ebf3.png">

**Comment by dimohamdy** [comment]
@darthpelo can you update to last version with Xcode 8 beta 6?

**Comment by dimohamdy** [comment]
@darthpelo please send pull request to @Constantine-Fry  repo

**Comment by darthpelo** [comment]
@dimohamdy I apologize for the delay, a little bit busy with my work. I am working on it, also regarding @benguild comment.

**Comment by darthpelo** [comment]
@Constantine-Fry created PR for Swift 2.3 -> #61

**Comment by reinder42** [comment]
Any idea when #63 is ready?

**Comment by MillerApps** [comment]
Is this still in the pipeline?

**Comment by benguild** [comment]
I think @Constantine-Fry is AWOL. Maybe we should start a fork elsewhere and just credit him?

**Comment by reinder42** [comment]
@benguild Agreed. Any takers? Happy to do it.

**Comment by benguild** [comment]
@reinderdevries Go for it. We can all contribute if you need help.

**Comment by constantine-fry** [comment]
The PR was merge. Feel free to make PR, I will merge it :)

**Comment by billy84** [comment]
How can I use it in Objective-C project?
I am working on xCode 8.0

Can you help me?

**Comment by benguild** [comment]
@billy84 You need to write a Swift wrapper for your needs that you can address from Objective-C. See this closed issue: https://github.com/Constantine-Fry/das-quadrat/issues/27

**Comment by billy84** [comment]
Thanks @benguild 
I did so. But I got this error : "Module 'QuadratTouch' not found"

Any idea?

**Comment by benguild** [comment]
@billy84 That means you haven't bundled the Cocoa Pod as a Framework. If you need specific help, post in the other issue if it's related to Objective-C, but this is not a Cocoa Pod support forum... nor is it on topic with migration to Swift 3.

**Comment by billy84** [comment]
Should I convert the project to Swift 3 after installing this pod?

**Comment by benguild** [comment]
@billy84 If you do, please submit a pull request to the repo with your changes for us to review.

**Comment by constantine-fry** [comment]
The `develop` branch has already Swift 3.0 support, the master `branch` is still with Swift 2.0. Once I test the swift 3.0 migration properly I will merge it to `master`.

![screen shot 2016-10-06 at 11 41 20](https://cloud.githubusercontent.com/assets/239692/19147783/ff71cd16-8bb9-11e6-9623-8f1c38f66637.png)

**Comment by benguild** [comment]
In that case, @billy84 why don't you just point your Cocoa Pod install at that branch instead?

**Comment by billy84** [comment]
Thanks.
It is working with develop branch.
By the way, I am not sure how I can use it.
Basically, how can I create Client for configuration?
If you have objective-c project, please share me some part

Thanks

**Comment by benguild** [comment]
@billy84 Can you post in the Objective-C issue instead? I think I already mentioned it. Thanks.

**Comment by billy84** [comment]
Oh, sorry about that. Will do so
