### ISSUE TITLE
Using in Objective-C project

### ISSUE THREAD

**Issue by billy84** [Constantine-Fry/das-quadrat#66]
I am working on Objective-C project with xCode 8.
I am not sure how I can use this pod in Obj-C project.
Basically, how can I create Client for configuration?
If you have sample code, please share me some code part.

Thanks

**Comment by benguild** [comment]
Duplicate of https://github.com/Constantine-Fry/das-quadrat/issues/27#issuecomment-252148912
@billy84  Can you close this?

**Comment by billy84** [comment]
Ok
